account:
  username: ""
  password: ""
  show_online_status: true

overall:
  play_finished_sound: true

imvu_next:
  # Adicione suas configurações aqui

people_search:
  # Adicione suas configurações aqui

unfollow:
  # Adicione suas configurações aqui
